### ISSUE TITLE
[Feature Request] ingress.hostname change default value from "app.local" to "null"

### ISSUE THREAD

**Issue by 3deep5me** [companyinfo/helm-charts#11]
Hi Folks,

really nice work, i use the tool literally for 30 minutes and its awesome!

I have an idea which i think could make the usage for the end user simpler again.
At the moment if you enable the ingress creation you have to change hostname and have to set an entry in your hosts file or in the DNS server to the IP of the Ingress-Controller to view the application. 

If the hostname value would be null in the ingress resource its possible to connect to the application direct over the IP without to configure a DNS-Entry or add an entry to the hosts file. 

The value has to be configured anyways for proper use but when the value is null you can view your application before you have to configure a DNS-Entry. So the process to get something running is simpler. 

The last time i used the [Bitnami Keycloak](https://github.com/bitnami/charts/tree/main/bitnami/keycloak) chart it does the same on default.

For me I like to go from a simple working configuration to a more advanced configuration step by step. I assume this could also be the case for a k8s-new🐝.

In my particular example, my values.yaml with the suggested change could look like this. It enables to access the app over the IP of the ingress controller:
```
image:
  repository: nginx

ports:
  - name: http
    containerPort: 80

ingress:
  enabled: true
```
Instead of this:
```
image:
  repository: nginx

ports:
  - name: http
    containerPort: 80

ingress:
  enabled: true
  hostname: "null"
```
