### ISSUE TITLE
Add option for multiple ingresses objects

### ISSUE THREAD

**Issue by yahel2410** [companyinfo/helm-charts#16]
Hi, I have a use-case where I need to deploy 2 ingresses for the same service, with different `annotations` per each ingress. 
In particular I'm trying the set `nginx.ingress.kubernetes.io/auth-url` for one ingress and don't set it for the other.

Can you please add support for multiple ingresses objects?

**Comment by p-afraz** [comment]
Hi, so is this what you suggest to be supported in the values file?

current:
```yaml
ingress:
    enabled: true
    annotations:
        nginx.ingress.kubernetes.io/auth-url: http://test.com/foo
```

new:
```yaml
ingress:
    - annotations:
           nginx.ingress.kubernetes.io/auth-url: http://test.com/foo
    - annotations:
           nginx.ingress.kubernetes.io/auth-url: http://test.com/bar
```

**Comment by yahel2410** [comment]
Hey, yes something like that. 
I suggest to accept a list of ingresses and create an Ingress object for each of them.
I my case the 2nd ingress doesn't need the `auth-url` annotation.

 e.g:

current:
```
ingress:
  enabled: true
  path: /foo
  hostname: "a.example.com"
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://test.com/foo

```
new:

```
ingress:
  - enabled: true
    path: /foo
    hostname: "a.example.com"
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/auth-url: http://test.com/foo
  - enabled: true
    path: /bar
    hostname: "a.example.com"
    ingressClassName: "nginx"
```
