### ISSUE TITLE
resources included only when defined in direct Helm values

### ISSUE THREAD

**Issue by alexfouche** [companyinfo/helm-charts#29]
_Maybe this is on purpose, but it does not make sense to me_

Context:

I am writing an Helm chart `mychart`, which as a dependency uses Helmet besides Redis Helm chart for example. So in the `mychart/values.yaml` (which acts as the defaults) of my Helm chart, i set all the top level values that Helmet expects, for example:

`mychart/Chart.yaml`:
```
(...)
name: mychart
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.1.1
  - name: helmet
    version: 0.9.1
    repository: https://companyinfo.github.io/helm-charts
    import-values: # <== It is mandatory if you want to import the Helmet default values.
      - defaults
  - name: common
    version: 2.x.x
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - bitnami-common
```

`mychart/values.yaml`:
```
image:
  repository: nginx

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /opt/plugandwork/apps/rce/current/tmp
```

These should act as the defaults, so i do not have to give any values when i run `helm install mychart`

Problem:

Helmet does not create any Deployment, nor Volumes in the Deployment config

To make it work, i have to remove the settings from `mychart/values.yaml` and set them into a top level `myvalues.yaml` file given to Helm with `helm install --values myvalues.yaml mychart`

To my understanding, this makes Helmet quite unusable for more complex apps written on other dependency Helm charts

Or maybe i am using Helmet wrong, if then what is the correct way ?
